### PR TITLE
remove random-source dependency

### PR DESCRIPTION
**Pull request by ruby0b**
random-source won't build with ghc-9.2 for me and since it's deprecated anyway I completely removed it.

(I also realized that it made no sense to guard the code with CPP pragmas if I remove the dependency from the cabal file)

### CODE REVIEW

**Comment by ruby0b** [comment]
Btw I don't know what the original motivation was for separating polysemy-randomfu from polysemy-zoo.
But if it was related to complexity it might be nice to merge this into the zoo since this package is very small now.

**Comment by adamConnerSax** [comment]
I think originally Sandy thought it added too many (transitive) dependencies and he didn't want that in the zoo.  Not sure if that has changed as random-fu changed.

My only issue with removing random-source vs. guarding the code, is backward compatibility for people using a version of random-fu that still uses random-source and who thus might want the constraint absorber machinery.  TBH, I haven't really thought through how versioning might make this a non-issue.

**Comment by ruby0b** [comment]
polysemy-randomfu absolutely can't depend on random-source in the future as it just won't build on newer GHC versions.
So as far as I can tell the only 2 options are:
1. Remove the dependency like I did in this PR (users of older random-fu versions would use an older version of polysemy-randomfu)
2. Guard the dependency with a flag in the cabal file

Unfortunately I don't think it's possible to check for other package versions in the cabal file so a manual flag would have to do in case of option [2].
I would suggest option [1] though since random-source is deprecated so it's not like there would be a reason to support it in future releases (older releases are still available on hackage after all so this won't break anything).

**Comment by adamConnerSax** [comment]
Sorry to have let this languish a bit.  It's fine to drop random-source.  But I'd like to retain the ability to run this with an entropy source other than the default IO source from system-random.  So I'm going to merge this and then try to add that back in.

First attempt here: https://github.com/adamConnerSax/polysemy-Extra/blob/master/polysemy-RandomFu/src/Polysemy/RandomFu.hs
Still needs tests.  And some thinking about the various ways of making it atomic and what those mean.

**Pull request merged**
